name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Build and test
      run: |
        pwd
        ls -l src/assignments
        g++ -std=c++17 $(find src/assignments -name '*.cpp') -o main



        
